'''
AUTODOWNLOADER FILE SUBMISI PENGKOM
BY HAFID ABI D
'''

'''
SHEET CODE ADALAH KODE UNIK PADA URL DARI GOOGLE SPREADSHEET
MISAL URL SPREADSHEET ADALAH =>
 https://docs.google.com/spreadsheets/d/1z8Z7B8zvnwqclLnA5XYANedYfXxcvFPzix4x9UaCM-E/edit#gid=156742627
MAKA SHEET CODENYA ADALAH =>
 1z8Z7B8zvnwqclLnA5XYANedYfXxcvFPzix4x9UaCM-E
'''
SHEET_CODE_PRAKTIKUM=""
SHEET_CODE_PENILAIAN=""
'''=================================================================================================================='''
'''
RANGE NIM ADALAH RANGE NIM DARI KELAS YANG KALIAN ASISTENI, [RANGE BAWAH-RANGE ATAS]
KALIAN BISA MENAMBAHKAN JUGA MENAMBAHKAN NIM DILUAR RANGE JUGA.
APABILA ADA NIM DALAM RANGE YANG INGIN DIHAPUS KARENA MHS TERSEBUT KELUAR DARI ITB ATAU HAL LAIN, TENANG KARENA KASUS TERSEBUT SUDAH
AKAN DITANGANI OLEH SISTEM KAMI DENGAN MENGECEK NIM YANG TIDAK ADA SUBMISINYA DAN AKAN MENGABAIKAN NIM TSB
'''
RANGE_NIM_BAWAH = 16520072
RANGE_NIM_ATAS = 16520142
ADDITIONAL_NIM = []
'''=================================================================================================================='''
'''
DEADLINE TP DAN DEADLINE PRAK ADALAH DEADLINE SUBMISI, SISTEM AKAN MELAKUKAN PEMILIHAN GDRIVE DENGAN SUBMISI TERBARU
DENGAN SYARAT:
    1. DIKIRIMKAN SEBELUM DEADLINE (TP DAN PRAK)
    2. UNTUK PRAKTIKUM JUGA DILAKUKAN PENGECEKAN APAKAH SUBMISI SETELAH SUBMISI SEBELUMNYA DIKIRIMKAN SEBELUM SPANTIME

SPANTIME ADALAH JARAK WAKTU ANTARA SUBMISI DENGAN SUBMISI SETELAHNYA UNTUK MENGHINDARI KEMUNGKINAN PRAKTIKAN UPLOAD
LAGI SETELAH KELUAR RUANGAN MS-TEAMS

ATURAN PENGISIAN
DEADLINE_TP DAN DEADLINE_PRAK ADALAH STRING DENGAN FORMAT "BULAN/TANGGAL/TAHUN JAM:MENIT:DETIK"
CONTOH => "10/21/2020 08:30:00" , MAKA SUBMISI SETELAH 21 OKTOBER 2020 8.30.00 AKAN DIMARK TELAT
          "11/29/2020 23:59:59" , MAKA SUBMISI SETELAH 29 NOV 2020 23.59.59 AKAN DIMARK TELAT

UNTUK PENGISIAN SPANTIME ADALAH DALAM SATUAN INTEGER DAN MEREPRESENTASIKAN DETIK
CONTOH => SPANTIME=1200, MAKA SPAN SUBMISI ADALAH 20 MENIT. APABILA JARAK SUBMIT DENGAN SUBMIT SETELAHNYA LEBIH DARI
            20 MENIT MAKA TIDAK AKAN DITERIMA, DAN YANG DITERIMA ADALAH SUBMISI SEBELUMNYA. KARENA ASUMSI MUNGKIN
            SAJA PRAKTIKAN TELAH MENINGGALKAN RUANGAN
            
NB = SPANTIME JUGA DAPAT DIADJUST SESUAI KEBIJAKAN ASISTEN 
'''
DEADLINE_TP="10/20/2020 23:59:59"
DEADLINE_PRAK = "10/21/2020 09:30:00"
SPANTIME = 1203
'''================================================================================================================'''
'''
INFORMASI TETANG BASIC PRAKTIKUM
PRAKTIKUM_KE DIISI PRAKTIKUM KE 1 S.D 5
SESI DIISI OLEH SESI ANDA, MISAL "3.1" ATAU "1.1" ATAU "4.3" ATAU LAINYA
KELAS DIISI OLEH KELAS DIMANA ANDA MENGISI, MISAL "A" ATAU "B" ATAU LAINYA
SESI DAN KELAS DITULIS DALAM STRING BUKAN InTeGeR
'''
PRAKTIKUM_KE = 1
SESI = "3.1"
KELAS = "B"
'''================================================================================================================'''
'''
DOWNLOAD_TP, APAKAH ANDA MAU MENDOWNLOAD SEMUA TP. BERI False JIKA ANDA TIDAK MAU MENDOWNLOAD TP PRAKTIKAN
DOWNLOAD_PRAK, APAKAH ANDA MAU DOWNLOAD SEMUA HASIL PRAKTIKUM. BERI False BILA TIDAK MAU DOWNLOAD FILE PRAKTIKUM
'''
DOWNLOAD_TP = True
DOWNLOAD_PRAK = True
